name: check-stock

on:
  schedule:
    - cron: "*/1 * * * *"  # 毎分
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 軽量チェック（requests + 条件付きGET + ジッター）
      - name: Restore caches (state & headers)
        id: restore-caches
        uses: actions/cache/restore@v4
        with:
          path: |
            state.json
            headers_cache.json
          key: restock-combined-v1

      - name: Run lightweight checker
        run: |
          [ -f state.json ] || echo "{}" > state.json
          [ -f headers_cache.json ] || echo "{}" > headers_cache.json
          python check_stock_light.py

      - name: Save caches after light check
        if: always()
        uses: actions/cache/save@v4
        with:
          path: |
            state.json
            headers_cache.json
          key: restock-combined-v1

      # Playwright は必要時のみセットアップ
      - name: Check trigger
        id: need-confirm
        run: |
          if [ -s needs_confirm.json ]; then
            echo "trigger=true" >> $GITHUB_OUTPUT
            echo "Will run heavy confirm via Playwright"
          else
            echo "trigger=false" >> $GITHUB_OUTPUT
            echo "No heavy confirm needed"
          fi

      - name: Setup Playwright
        if: steps.need-confirm.outputs.trigger == 'true'
        uses: microsoft/playwright-github-action@v1

      - name: Heavy confirm (Playwright) + notify
        if: steps.need-confirm.outputs.trigger == 'true'
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_TO_USER_ID: ${{ secrets.LINE_TO_USER_ID }}
        run: |
          python check_stock_playwright.py

      - name: Save caches after heavy confirm
        if: always()
        uses: actions/cache/save@v4
        with:
          path: |
            state.json
            headers_cache.json
          key: restock-combined-v1
